### ISSUE TITLE
browser: InfluxDBClient constructor using string parameter requires full URL

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-js#213]
### Specifications

* Client Version: 0.5.0
* InfluxDB Version: IOX
* Platform: Ubuntu 22.04.3, Nodejs 21.4.0, Vite 4.4.12

### Code sample to reproduce problem

```javascript
const DATABASE = import.meta.env.VITE_INFLUX_DB
const TOKEN = import.meta.env.VITE_INFLUX_TOKEN
const HOST='/influx'

...

        const connectString = `${HOST}?token=${TOKEN}`
        console.log("Connecting with string: " + connectString)
        client = new InfluxDBClient(connectString)

```

Note that `HOST` is setup to use an Envoy proxy to connect to Influx.  

See additional info below for proxy configuration. 

### Expected behavior

Since the following using configuration properties works: 

```js
client = new InfluxDBClient({host: HOST, token: TOKEN})
```
... expected that the string argument in the InfluxDBClient constructor would also work. 

### Actual behavior

Throws the following exception in the browser

```
@influxdata_influxdb3-client-browser.js?v=94b8760b:13466 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at et (@influxdata_influxdb3-client-browser.js?v=94b8760b:13466:44)
    at new he (@influxdata_influxdb3-client-browser.js?v=94b8760b:15891:39)
    at index.js:25:18
```

### Additional info

**Work around**

Use the IncldDBClient constructor using options.  Or, use the full hostname in the connection string. 

e.g.
```js
        const connectString = `http://localhost:5173${HOST}?token=${TOKEN}`
        console.log("Connecting with string: " + connectString)
        client = new InfluxDBClient(connectString)
```

**Proxy config files**
vite.config.js
```js
import {defineConfig} from 'vite'

export default defineConfig({
    server: {
        proxy: {
            '/influx': {
                target: 'http://localhost:10000', // envoy address
                changeOrigin: true,
                rewrite: (path) => path.replace(/^\/influx/, '')
            }
        }
    }
})
``` 
envoy.yaml
```yaml
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
      - filter_chain_match:
        filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
                - name: envoy.filters.http.grpc_web
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                - name: envoy.filters.http.cors
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match: { prefix: "/" }
                        route:
                          cluster: influxdb_cluster
                          prefix_rewrite: "/"
                          auto_host_rewrite: true
                          timeout: 10s
                    cors:
                      allow_origin_string_match:
                        - prefix: "*"
                      allow_methods: GET, PUT, DELETE, POST, OPTIONS

  clusters:
    - name: influxdb_cluster
      connect_timeout: 10s
      type: STRICT_DNS
      load_assignment:
        cluster_name: influxdb_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "us-east-1-1.aws.cloud2.influxdata.com"
                      port_value: 443
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            alpn_protocols: [ "h2,http/1.1" ]

```
